name: Crear APK MateLabs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Crear proyecto Android
        run: npx cap add android

      - name: Copiar MateLabs
        run: npx cap sync android

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Crear APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: MateLabs-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
